# Generated by Django 2.1.7 on 2020-02-26 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('message_ar', models.TextField(null=True)),
                ('message_en', models.TextField(null=True)),
                ('action', models.IntegerField(choices=[(0, 'No action'), (1, 'Question liked'), (2, 'Question shared'), (3, 'Got a comment'), (8, 'New comment on followed question'), (4, 'Useful comment'), (5, 'Got followed'), (6, 'Question favourite'), (7, 'Followed user added new recipe')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Passed to pushy'), (2, 'Delivered'), (3, "Faild as user hasn't notification token"), (4, 'Pushy Faild'), (5, 'Unknown Error'), (6, 'Template action not exist please add one')], default=0)),
                ('fb_response', models.TextField(null=True)),
                ('seen', models.BooleanField(default=False)),
                ('extra_data', models.CharField(max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_template', models.CharField(max_length=100, null=True)),
                ('title_template_ar', models.CharField(max_length=100, null=True)),
                ('title_template_en', models.CharField(max_length=100, null=True)),
                ('message_template', models.TextField(null=True)),
                ('message_template_ar', models.TextField(null=True)),
                ('message_template_en', models.TextField(null=True)),
                ('action', models.IntegerField(choices=[(0, 'No action'), (1, 'Question liked'), (2, 'Question shared'), (3, 'Got a comment'), (8, 'New comment on followed question'), (4, 'Useful comment'), (5, 'Got followed'), (6, 'Question favourite'), (7, 'Followed user added new recipe')], default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushyToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushy_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
