# Generated by Django 2.1.7 on 2020-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200226_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_chn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_esp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_in',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_jp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_kp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_kr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_pe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_vn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_chn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_esp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_in',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_jp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_kp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_kr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_pe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_vn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_chn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_esp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_in',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_jp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_kp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_kr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_pe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_vn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_chn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_esp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_in',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_jp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_kp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_kr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_pe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_vn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
