# Generated by Django 2.1.7 on 2020-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200314_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.IntegerField(choices=[(0, 'No action'), (1, 'Question liked'), (2, 'Question shared'), (3, 'Got a comment'), (8, 'New comment on followed question'), (4, 'Useful comment'), (5, 'Got followed'), (6, 'Question favourite'), (7, 'Followed user added new question'), (9, 'Got a reply to your comment')], default=0),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='action',
            field=models.IntegerField(choices=[(0, 'No action'), (1, 'Question liked'), (2, 'Question shared'), (3, 'Got a comment'), (8, 'New comment on followed question'), (4, 'Useful comment'), (5, 'Got followed'), (6, 'Question favourite'), (7, 'Followed user added new question'), (9, 'Got a reply to your comment')], default=0, unique=True),
        ),
    ]
