# Generated by Django 2.1.7 on 2020-03-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200322_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message_my',
            new_name='message_es',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title_my',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='message_template_my',
            new_name='message_template_es',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='title_template_my',
            new_name='title_template_es',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_zn_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_zn_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_zn_tw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_zn_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_zn_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_zn_tw',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
