# Generated by Django 2.1.7 on 2020-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20200330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message_template_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template_vi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
