# Generated by Django 2.1.7 on 2020-02-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20200203_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
    ]
