# Generated by Django 2.1.7 on 2020-02-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_questionreply_parent_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreply',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='connect.Question'),
        ),
    ]
