# Generated by Django 2.1.7 on 2020-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20200204_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreply',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_image/'),
        ),
        migrations.AlterField(
            model_name='questionreply',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
