# Generated by Django 2.1.7 on 2020-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20200204_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
    ]
