# Generated by Django 2.1.7 on 2020-02-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200204_1504'),
        ('connect', '0009_remove_question_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='accounts.Language'),
        ),
    ]
