# Generated by Django 2.1.7 on 2020-02-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20200205_2130'),
        ('connect', '0010_question_language'),
    ]

    operations = [
    ]
