# Generated by Django 2.1.7 on 2020-02-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_merge_20200206_0715'),
        ('connect', '0011_merge_20200206_0516'),
    ]

    operations = [
    ]
