# Generated by Django 2.1.7 on 2020-03-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_auto_20200306_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_chn',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_esp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_in',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_jp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_kp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_kr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_pe',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_vn',
        ),
    ]
