# Generated by Django 2.1.7 on 2020-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0014_auto_20200310_1032'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_deleted',
        ),
    ]
