# Generated by Django 2.1.7 on 2020-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_auto_20200327_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order Number'),
        ),
    ]
