# Generated by Django 2.1.7 on 2020-03-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0017_auto_20200330_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_zn_ch',
            new_name='name_zh_hans',
        ),
    ]
