# Generated by Django 2.1.7 on 2020-02-06 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200204_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
    ]
