# Generated by Django 2.1.7 on 2020-03-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200206_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_my_followup_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_my_questions',
            field=models.BooleanField(default=True),
        ),
    ]
