# Generated by Django 2.1.7 on 2020-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200308_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
