# Generated by Django 2.1.7 on 2020-03-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_social_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_type',
            field=models.IntegerField(choices=[(0, 'No social'), (1, 'Facebook'), (2, 'wechat'), (2, 'Apple')], db_index=True, default=0),
        ),
    ]
