# Generated by Django 2.1.7 on 2020-03-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200314_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_type',
            field=models.IntegerField(choices=[(0, 'No social'), (1, 'Facebook'), (2, 'Wechat'), (3, 'Apple')], db_index=True, default=0),
        ),
    ]
