# Generated by Django 2.1.7 on 2020-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200314_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
