# Generated by Django 2.1.7 on 2020-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_language_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_name',
            field=models.CharField(default='translated', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_zn_ch',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_zn_tw',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
