# Generated by Django 2.1.7 on 2020-03-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200330_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_zn_ch',
            new_name='lang_name_zh_hans',
        ),
    ]
