# Generated by Django 2.1.7 on 2020-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_name_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_name_vi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
