# Generated by Django 2.1.7 on 2020-04-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200402_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_ar',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_de',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_es',
            new_name='name_es',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_fa',
            new_name='name_fa',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_fr',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_hi',
            new_name='name_hi',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_ind',
            new_name='name_ind',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_it',
            new_name='name_it',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_ja',
            new_name='name_ja',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_ko',
            new_name='name_ko',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_my',
            new_name='name_my',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_pt',
            new_name='name_pt',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_th',
            new_name='name_th',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_tr',
            new_name='name_tr',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_ur',
            new_name='name_ur',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_vi',
            new_name='name_vi',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_zh_hans',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name_zh_hant',
            new_name='name_zh_hant',
        ),
    ]
