# Generated by Django 2.1.7 on 2019-11-26 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='channels/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Text and video'), (1, 'Text and image'), (2, 'Only text')], db_index=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='posts/media/')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='revyoume_club.Channel')),
                ('liked_by_users', models.ManyToManyField(blank=True, related_name='my_liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevyoumeClubSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revyoume_club_link', models.URLField(null=True, verbose_name='Revyoume Club Link')),
                ('revyoume_club_enabled', models.BooleanField(default=True, verbose_name='Enable Revyoume Club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
