# Generated by Django 2.1.7 on 2020-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revyoume_club', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='youko url'),
        ),
    ]
