# Generated by Django 2.1.7 on 2020-02-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revyoume_club', '0003_auto_20200205_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='youko_link',
        ),
    ]
