# Generated by Django 2.1.7 on 2020-03-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revyoume_club', '0005_revyoumeclubsetting_youko_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in',
            field=models.IntegerField(choices=[(1, 'Media'), (2, 'Articles')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text and video'), (1, 'Text and image'), (2, 'Only text')], db_index=True, default=2),
        ),
    ]
